# Generated by Django 3.2 on 2021-08-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='images_profile'),
        ),
    ]
