# Generated by Django 3.2 on 2021-08-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0003_alter_appuser_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='appuser',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='ocupation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
