# Generated by Django 3.2 on 2021-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0005_alter_appuser_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images_profile'),
        ),
    ]
