# Generated by Django 3.2 on 2021-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0006_alter_appuser_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postDate',
            field=models.DateField(null=True),
        ),
    ]
