# Generated by Django 3.2 on 2021-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0007_alter_post_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
