# Generated by Django 3.2 on 2021-08-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0013_rename_friends_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
    ]
