# Generated by Django 3.2 on 2021-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0016_auto_20210831_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='chat_room',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
